apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: monitoring-discord
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: monitoring
    release: monitoring
spec:
  route:
    receiver: discord-webhook
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            matchType: "="
            value: Watchdog
    groupBy:
      - alertname
      - namespace
      - pod
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
  receivers:
    - name: "null"
    - name: discord-webhook
      slackConfigs:
        - apiURL:
            name: discord-webhook
            key: url
          fallback: "Alert {{`{{ .CommonLabels.alertname }}`}} ({{`{{ .Status }}`}})"
          title: "[{{`{{ .Status | toUpper }}`}}] {{`{{ .CommonLabels.alertname }}`}}"
          text: >-
            alert={{`{{ .CommonLabels.alertname }}`}} status={{`{{ .Status }}`}}
            {{`{{ range .Alerts }}`}}
            - {{`{{ if .Annotations.summary }}`}}{{`{{ .Annotations.summary }}`}}{{`{{ else }}`}}{{`{{ .Labels.alertname }}`}}{{`{{ end }}`}}
            {{`{{ if .Annotations.description }}`}} | {{`{{ .Annotations.description }}`}}{{`{{ end }}`}}
            {{`{{ end }}`}}
          sendResolved: true
