apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: monitoring-discord
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/part-of: monitoring
    release: monitoring
spec:
  route:
    receiver: discord-webhook
    routes:
      - receiver: "null"
        matchers:
          - name: alertname
            matchType: "="
            value: Watchdog
    groupBy:
      - alertname
      - namespace
      - pod
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 4h
  receivers:
    - name: "null"
    - name: discord-webhook
      slackConfigs:
        - apiURL:
            name: discord-webhook
            key: url
          title: "[{{`{{ .Status | toUpper }}`}}] {{`{{ .CommonLabels.alertname }}`}}"
          text: >-
            {{`{{ range .Alerts }}`}}
            *{{`{{ .Annotations.summary }}`}}*
            {{`{{ .Annotations.description }}`}}
            labels: {{`{{ .Labels }}`}}
            {{`{{ end }}`}}
          sendResolved: true
